version: "3.7"
services:
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: shiny

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

  shiny:
    environment:
      - DATABASE="db"
    build: ./shiny/
    restart: always
    volumes:
      # - ./shiny/config:/etc/shiny-server # убираем веб-сокеты из конфига
      - ./shiny/shiny_logs:/var/log/shiny-server # логи
      - ./shiny/shinyapps:/srv/shiny-server # файлы приложения
    ports:
      - 3838:3838